//
//  CategoryProductsWorkerTests.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 07/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import LodjinhaSZ
import XCTest

class CategoryProductsWorkerTests: XCTestCase
{
	// MARK: Subject under test
	
	var sut: CategoryProductsWorker!
	
	// MARK: Test lifecycle
	
	override func setUp() {
		
		super.setUp()
		setupCategoryProductsWorker()
	}
	
	override func tearDown() {
		
		super.tearDown()
	}
	
	// MARK: Test setup
	
	func setupCategoryProductsWorker() {
		
		sut = CategoryProductsWorker(CategoryProductsNetworkWorkerSpy())
	}
	
	// MARK: Test doubles
	
	class CategoryProductsNetworkWorkerSpy: CategoryProductsNetworkWorker {
		
		var networkCalled = false
		override func getProducts(ofCategory categoryId: Int,
								  withOffset offset: Int,
								  andLimit limit: Int,
								  completion: @escaping (() throws -> ProductList) -> Void) {
			
			networkCalled = true
			completion { return Seeds.NetworkModels.networkProductList }
		}
	}
	
	// MARK: Tests
	
	func testGetCategoryProducts() {
		
		// Given
		let networkWorker = sut.categoryProductsWorker as! CategoryProductsNetworkWorkerSpy
		
		// When
		let expect = expectation(description: "Wait for API result to return")
		sut.getProducts(ofCategory: 9, withOffset: 0, andLimit: 20) { (productList, error) in
			
			expect.fulfill()
		}
		waitForExpectations(timeout: 1.1)
		
		// Then
		XCTAssertTrue(networkWorker.networkCalled, "getProducts() should ask API for category's products")
	}
}
