//
//  CategoryProductsRouter.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 05/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CategoryProductsRoutingLogic {
	func routeToCategoryProductDetail(segue: UIStoryboardSegue?)
}

protocol CategoryProductsDataPassing {
	var dataStore: CategoryProductsDataStore? { get }
}

class CategoryProductsRouter: NSObject, CategoryProductsRoutingLogic, CategoryProductsDataPassing {
	
	weak var viewController: CategoryProductsViewController?
	var dataStore: CategoryProductsDataStore?
	
	// MARK: Routing
	
	func routeToCategoryProductDetail(segue: UIStoryboardSegue?) {
		
		if let segue = segue {
		
			let destinationVC = segue.destination as! ProductDetailViewController
			var destinationDS = destinationVC.router!.dataStore!
			passDataToCategoryProductDetail(source: dataStore!, destination: &destinationDS)
		}
	}
	
	
	// MARK: Passing data
	
	func passDataToCategoryProductDetail(source: CategoryProductsDataStore, destination: inout ProductDetailDataStore) {
		
		destination.product = source.product
	}
}
