//
//  CategorysProductsWorker.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 05/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CategorysProductsWorker {
	
	var categorysProductsWorker:CategorysProductsWorkerProtocol
	
	init(_ categorysProductsWorker:CategorysProductsWorkerProtocol) {
		
		self.categorysProductsWorker = categorysProductsWorker
	}
	
	func getProducts(ofCategory categoryId:Int, withOffset offset:Int, andLimit limit:Int, completion:@escaping(ProductList?,Error?) -> Void) {
	
		categorysProductsWorker.getProducts(ofCategory: categoryId, withOffset: offset, andLimit: limit) { (categorysProducts: () throws -> ProductList) in
		
			do{
				let categorysProducts = try categorysProducts()
				completion(categorysProducts,nil)
			}catch let error{
				completion(nil, WorkerErrors.networkProblem(error: error))
			}
		}
	}
}

protocol CategorysProductsWorkerProtocol {
	func getProducts(ofCategory categoryId:Int, withOffset offset:Int, andLimit limit:Int, completion:@escaping(() throws -> ProductList) -> Void)
}
