//
//  CategorysProductsPresenter.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 05/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategorysProductsPresentationLogic {
	func presentCategorysProducts(response: CategorysProducts.getCategorysProducts.Response)
}

class CategorysProductsPresenter: CategorysProductsPresentationLogic {
	
	weak var viewController: CategorysProductsDisplayLogic?
	
	// MARK: Get Category's Products
	
	func presentCategorysProducts(response: CategorysProducts.getCategorysProducts.Response) {
		
		let viewModel = CategorysProducts.getCategorysProducts.ViewModel(products: nil, offset: nil, total: nil, error: nil)
		viewController?.displayProducts(viewModel: viewModel)
	}
}
