//
//  CategorysProductsInteractor.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 05/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategorysProductsBusinessLogic {
	func getCategorysProducts(request: CategorysProducts.getCategorysProducts.Request)
}

protocol CategorysProductsDataStore {
	var category	: CategoryViewModel? 	{ get set }
	var product		: ProductViewModel? 	{ get set }
}

class CategorysProductsInteractor: CategorysProductsBusinessLogic, CategorysProductsDataStore {
	
	var presenter	: CategorysProductsPresentationLogic?
	var worker		: CategorysProductsWorker?
	
	var category	: CategoryViewModel?
	var product		: ProductViewModel?
	
	// MARK: Do something
	
	func getCategorysProducts(request: CategorysProducts.getCategorysProducts.Request) {
		
		worker = CategorysProductsWorker()
		worker?.doSomeWork()
		
		let response = CategorysProducts.getCategorysProducts.Response(products: nil, error: nil)
		presenter?.presentCategorysProducts(response: response)
	}
}
