//
//  CategoryProductsRouter.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 05/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CategoryProductsRoutingLogic {
	//func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CategoryProductsDataPassing {
	var dataStore: CategoryProductsDataStore? { get }
}

class CategoryProductsRouter: NSObject, CategoryProductsRoutingLogic, CategoryProductsDataPassing {
	
	weak var viewController: CategoryProductsViewController?
	var dataStore: CategoryProductsDataStore?
	
	// MARK: Routing
	
	//func routeToSomewhere(segue: UIStoryboardSegue?)
	//{
	//  if let segue = segue {
	//    let destinationVC = segue.destination as! SomewhereViewController
	//    var destinationDS = destinationVC.router!.dataStore!
	//    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
	//  } else {
	//    let storyboard = UIStoryboard(name: "Main", bundle: nil)
	//    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
	//    var destinationDS = destinationVC.router!.dataStore!
	//    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
	//    navigateToSomewhere(source: viewController!, destination: destinationVC)
	//  }
	//}
	
	// MARK: Navigation
	
	//func navigateToSomewhere(source: CategoryProductsViewController, destination: SomewhereViewController)
	//{
	//  source.show(destination, sender: nil)
	//}
	
	// MARK: Passing data
	
	//func passDataToSomewhere(source: CategoryProductsDataStore, destination: inout SomewhereDataStore)
	//{
	//  destination.name = source.name
	//}
}
