//
//  HomeModels.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 02/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
	
	enum GetBannerList {
		
		struct Request {
			
		}
		
		struct Response {
			
			var banners:BannerList?
			var error:Error?
		}
		
		struct ViewModel {
			
			var banners:[BannerViewModel]?
			var error:Error?
		}
	}
	
	enum GetCategoryList {
		
		struct Request {
			
			
		}
		struct Response {
			
			var categories:CategoryList?
			var error:Error?
		}
		struct ViewModel {
			
			var categories:[CategoryViewModel]?
			var error:Error?
		}
	}
	
	enum GetPopProductList {
		
		struct Request {
			
			
		}
		struct Response {
			
			var popProducts:ProductList?
			var error:Error?
		}
		struct ViewModel {
			
			var popProducts:[ProductViewModel]?
			var error:Error?
		}
	}
	
	enum ShowNextScreen {
		
		struct Request {
			
			var nextScreen:NextScreen
		}
		
		struct Response {
			
			var nextScreen:NextScreen
		}
		
		struct ViewModel {
			
			var nextScreen:NextScreen
		}
	}
}

struct BannerViewModel {
	
	let bannerImageUrl	:String?
	let bannerLink		:String?
}

struct CategoryViewModel:Equatable {
	
	let id					: Int?
	let desc				: String?
	let categoryImageUrl	: String?
	
	static func == (lhs: CategoryViewModel, rhs: CategoryViewModel) -> Bool {
		
		return lhs.id == rhs.id &&
			lhs.desc == rhs.desc &&
			lhs.categoryImageUrl == rhs.categoryImageUrl
	}
}

struct ProductViewModel:Equatable {
	
	let category		: CategoryViewModel?
	let desc			: String?
	let id				: Int?
	let name			: String?
	let originalPrice	: String?
	let price			: String?
	let imageUrl		: String?
	let isPromotion		: Bool
	
	static func == (lhs: ProductViewModel, rhs: ProductViewModel) -> Bool {
		
		return lhs.id == rhs.id &&
			lhs.desc == rhs.desc &&
			lhs.category == rhs.category &&
			lhs.name == rhs.name &&
			lhs.originalPrice == rhs.originalPrice &&
			lhs.price == rhs.price &&
			lhs.imageUrl == rhs.imageUrl &&
			lhs.isPromotion == rhs.isPromotion
	}
}
