//
//  HomeModels.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 02/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
	
	enum GetBannerList {
		
		struct Request {
			
		}
		
		struct Response {
			
			var banners:BannerList?
			var error:Error?
		}
		
		struct ViewModel {
			
			var banners:[BannerViewModel]?
			var error:Error?
		}
	}
	
	enum CategoryList {
		
		struct Request {
			
			
		}
		struct Response {
			
			
		}
		struct ViewModel {
			
			
		}
	}
	
	enum ProductList {
		
		struct Request {
			
			
		}
		struct Response {
			
			
		}
		struct ViewModel {
			
			
		}
	}
}

struct BannerViewModel {
	
	var bannerImage		:UIImage?
	var bannerLink		:String?
}
