//
//  HomeRouter.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 02/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
	func routeToCategoryProducts(segue: UIStoryboardSegue?)
//	func routeToProductDetail(segue: UIStoryboardSegue?)
}

protocol HomeDataPassing {
	var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
	
	weak var viewController: HomeViewController?
	var dataStore: HomeDataStore?
	
	// MARK: Routing
	
	func routeToCategoryProducts(segue: UIStoryboardSegue?) {
		
		if let segue = segue {
			
			let destinationVC = segue.destination as! CategoryProductsViewController
			var destinationDS = destinationVC.router!.dataStore!
			passDataToCategoryProducts(source: dataStore!, destination: &destinationDS)
		}
	}
	
//	func routeToProductDetail(segue: UIStoryboardSegue?) {
//
//		if let segue = segue {
//
//			let destinationVC = segue.destination as! ProductDetailViewController
//			var destinationDS = destinationVC.router!.dataStore!
//			passDataToProductDetail(source: dataStore!, destination: &destinationDS)
//		}
//	}
	
	// MARK: Passing data
	
	func passDataToCategoryProducts(source: HomeDataStore, destination: inout CategoryProductsDataStore) {
		
		destination.category = source.category
	}
	
//	func passDataToProductDetail(source: HomeDataStore, destination: inout ProductDetailDataStore) {
//
//		destination.product = source.popProduct
//	}
}
