//
//  HomeModels.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 02/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
	
	enum GetBannerList {
		
		struct Request {
			
		}
		
		struct Response {
			
			var banners:BannerList?
			var error:Error?
		}
		
		struct ViewModel {
			
			var banners:[BannerViewModel]?
			var error:Error?
		}
	}
	
	enum GetCategoryList {
		
		struct Request {
			
			
		}
		struct Response {
			
			var categories:CategoryList?
			var error:Error?
		}
		struct ViewModel {
			
			var categories:[CategoryViewModel]?
			var error:Error?
		}
	}
	
	enum GetPopProductList {
		
		struct Request {
			
			
		}
		struct Response {
			
			
		}
		struct ViewModel {
			
			
		}
	}
}

struct BannerViewModel {
	
	var bannerImageUrl	:String?
	var bannerLink		:String?
}

struct CategoryViewModel {
	
	var id					: Int?
	var desc				: String?
	var categoryImageUrl	: String?
}
