//
//  HomeInteractor.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 02/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
	
	func getBanners(request: Home.GetBannerList.Request)
}

protocol HomeDataStore {
	
	//var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
	
	var presenter		: HomePresentationLogic?
	var worker			: HomeWorker?
	let bannerWorker	: BannerListNetworkWorker = BannerListNetworkWorker()
	//var name: String = ""
	
	// MARK: Get Banners
	
	func getBanners(request: Home.GetBannerList.Request) {

		worker = HomeWorker(bannerWorker, nil, nil)
		worker?.getBanners(completion: { (banners, error) in
			
			let response:Home.GetBannerList.Response
			
			if error == nil, let banners = banners {
				
				response = Home.GetBannerList.Response(banners: banners,error: nil)
			}else {
				
				response = Home.GetBannerList.Response(banners: nil, error: error)
			}
			
			self.presenter?.presentBanners(response: response)
		})
	}
}
