//
//  Banner.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 01/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import Foundation

struct Banner: Codable {
	
    let id			: Int?
	let linkUrl		: String?
	let urlImagem	: String?
}

struct BannerList: DataList {
	
	typealias T = Banner
	
	var data: [Banner]?
}
