//
//  Banner.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 01/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import Foundation

struct Banner: Codable {
	
    let id			: Int?
	let urlLink		: String?
	let imageUrl	: String?
	
	enum CodingKeys:String,CodingKey{
		
		case id
		case urlLink 	= "linkUrl"
		case imageUrl 	= "urlImagem"
	}
}

struct BannerList: DataList {
	
	typealias T = Banner
	
	var data: [Banner]?
}
