//
//  DataList.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 01/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import Foundation

protocol DataList:Codable {
	
	associatedtype T:Codable
	
	var data:[T]? {get}
}
