//
//  Product.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 01/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import Foundation

struct Product: Codable,CustomStringConvertible,Equatable {
	
    let category		: Category?
	let desc			: String?
	let id				: Int?
	let name			: String?
	let originalPrice	: Double?
	let price			: Double?
	let imageUrl		: String?
	
	var isPromotion:Bool {
		
		if let originalPrice = originalPrice, let price = price {
			
			return originalPrice != price
		}
		
		return false
	}
	
    enum CodingKeys:String,CodingKey{
        
        case category 		= "categoria"
		case desc			= "descricao"
		case id
		case name			= "nome"
		case originalPrice	= "precoDe"
		case price			= "precoPor"
		case imageUrl		= "urlImagem"
    }
	
    static func == (lhs: Product, rhs: Product) -> Bool {
    
        return lhs.id == rhs.id
    }
	
    var description: String {
		
		return "Produto \(self.id ?? -1): \(self.desc ?? "-")"
    }

}

struct ProductList: DataList {

	typealias T = Product
	
	var data: [Product]?
	
	let offset	: Int?
	let total	: Int?
}
