//
//  ProductDetailInteractor.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 06/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailBusinessLogic {
	func getProduct(request: ProductDetail.ProductDetail.Request)
}

protocol ProductDetailDataStore {
	var product:ProductViewModel? { get set }
}

class ProductDetailInteractor: ProductDetailBusinessLogic, ProductDetailDataStore {
	
	var presenter	: ProductDetailPresentationLogic?
	var product		: ProductViewModel?
	
	// MARK: Get Product
	
	func getProduct(request: ProductDetail.ProductDetail.Request) {
		
		let response = ProductDetail.ProductDetail.Response(product: self.product)
		presenter?.presentProductDetail(response: response)
	}
}
