//
//  ProductDetailPresenter.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 06/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailPresentationLogic {
	func presentProductDetail(response: ProductDetail.ProductDetail.Response)
}

class ProductDetailPresenter: ProductDetailPresentationLogic {
	
	weak var viewController: ProductDetailDisplayLogic?
	
	// MARK: Get Product
	
	func presentProductDetail(response: ProductDetail.ProductDetail.Response) {
		
		let viewModel = ProductDetail.ProductDetail.ViewModel(product: response.product)
		viewController?.displayProductDetail(viewModel: viewModel)
	}
}
