//
//  ProductDetailWorker.swift
//  LodjinhaSZ
//
//  Created by Tiago Chaves on 06/06/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProductDetailWorker {
	
	var productDetailWorker:ProductDetailWorkerProtocol
	
	init(_ productDetailWorker:ProductDetailWorkerProtocol) {
		
		self.productDetailWorker = productDetailWorker
	}
	
//	func getData(completion:@escaping(ReturnData?,Error?) -> Void) {
//
//		ProductDetailWorker.getData { (data: () throws -> ReturnData) in
//
//			do{
//				let returnData = try data()
//				completion(returnData,nil)
//			}catch let error{
//				completion(nil, error)
//			}
//		}
//	}
}

protocol ProductDetailWorkerProtocol {
//	func getData(completion:@escaping(() throws -> ReturnData) -> Void)
}
